HINDI_SYMPTOM_MAP = {
    "thakaan": "fatigue",
    "thaka": "fatigue",
    "kamzori": "fatigue",
    "weakness": "fatigue",
    "neend nahi": "insomnia",
    "neend nhi": "insomnia",
    "so nahi pata": "insomnia",
    "haddi dard": "bone_pain",
    "haddiyon mein dard": "bone_pain",
    "jodon mein dard": "joint_pain",
    "joint pain": "joint_pain",
    "sar dard": "headache",
    "sir dard": "headache",
    "headache": "headache",
    "baal girna": "hair_loss",
    "baal jhadna": "hair_loss",
    "baal gir rahe": "hair_loss",
    "baal jhadte": "hair_loss",
    "vaal jhadte": "hair_loss",
    "hair fall": "hair_loss",
    "hair falling": "hair_loss",
    "nails are brittle": "brittle_nails",
    "brittle nails": "brittle_nails",
    "nails breaking": "brittle_nails",
    "aankhein raat": "night_blindness",
    "raat ko kamzor": "night_blindness",
    "masude se khoon": "bleeding_gums",
    "masudo se khoon": "bleeding_gums",
    "nakhun toota": "brittle_nails",
    "nakhun tutna": "brittle_nails",
    "nakhun kamzor": "brittle_nails",
    "khaana na lagna": "loss_of_appetite",
    "bhook nahi": "loss_of_appetite",
    "chakkar": "dizziness",
    "chakkar aana": "dizziness",
    "sans lene mein takleef": "breathlessness",
    "saans phoolna": "breathlessness",
    "chehra safed": "pallor",
    "rang peela": "pallor",
    "aankhein peeli": "jaundice",
    "skin dry": "dry_skin",
    "khushki": "dry_skin",
    "rusi": "dry_skin",
    "daad": "skin_rashes",
    "kharish": "skin_rashes",
    "khujli": "skin_rashes",
    "zakhm nahi bharta": "slow_wound_healing",
    "ghao nahi bharta": "slow_wound_healing",
    "muh mein chhaale": "mouth_ulcers",
    "muh ke chhaale": "mouth_ulcers",
    "ulcer": "mouth_ulcers",
    "daant dard": "dental_problems",
    "mele daant": "dental_problems",
    "maasspeshiyon mein dard": "muscle_cramps",
    "takkar": "muscle_cramps",
    "pair mein dard": "muscle_cramps",
    "pair dard": "muscle_cramps",
    "haath pair thande": "cold_hands_feet",
    "haath thande": "cold_hands_feet",
    "yaad nahi rehta": "memory_issues",
    "bhoolna": "memory_issues",
    "concentration nahi": "memory_issues",
    "ghutan": "anxiety",
    "tension": "anxiety",
    "depression": "depression",
    "udaasi": "depression",
    "man udas": "depression",
    "aankhein kamzor": "vision_problems",
    "raat ko nahi dikhta": "night_blindness",
    "andhera lagta": "night_blindness",
    "aankhein sukhna": "dry_eyes",
    "aankhein jalna": "dry_eyes",
    "munde sukhna": "dry_eyes",
    "masude khoon": "bleeding_gums",
    "masude se blood": "bleeding_gums",
    "masudo se khoon": "bleeding_gums",
    "jibh laal": "sore_tongue",
    "jibh mein dard": "sore_tongue",
    "gale mein sujan": "goiter",
    "ganth gale mein": "goiter",
    "wajan badhna": "weight_gain",
    "mota hona": "weight_gain",
    "thand lagti": "cold_intolerance",
    "bahut thand": "cold_intolerance",
    "hath pair sunna": "numbness_tingling",
    "hath sunna": "numbness_tingling",
    "jhanjhanahat": "numbness_tingling",
    "sookha muh": "dry_mouth",
    "pyaas zyada": "increased_thirst",
    "peshab zyada": "frequent_urination",
    "khoon ki kami": "iron_deficiency",
    "anemia": "iron_deficiency",
    "khoon nahi": "iron_deficiency",
    "infection zyada": "frequent_infections",
    "beemar zyada": "frequent_infections",
    "bar bar beemar": "frequent_infections",
    "neend mein pareshani": "insomnia",
    "ankahin rona": "depression",
    "thoda khaana": "loss_of_appetite",
    "pet mein takleef": "abdominal_pain",
    "kabz": "constipation",
    "qabz": "constipation",
    "pait saaf nahi": "constipation",
    "dil ki dharkan": "irregular_heartbeat",
    "ghabharahat": "irregular_heartbeat",
    "sar ghoomna": "dizziness",
    "aankhon ke saamne andhera": "dizziness",
    "naakhun mein safed dabbe": "white_spots_nails",
    "naakhun pe dabbe": "white_spots_nails",
    "naakhun mein khaanche": "ridged_nails",
    "pair mein sujan": "edema",
    "sujan": "edema",
    "bhuri skin": "skin_rashes",
    "chehra sujha": "puffy_face",
    "aankhein sooji": "puffy_eyes",
    "bacho ki height nahi badh rahi": "poor_growth",
    "baccha nahi badh raha": "poor_growth",
}

PUNJABI_SYMPTOM_MAP = {
    "thakaan": "fatigue",
    "thaka hoya": "fatigue",
    "kamzori": "fatigue",
    "neend nahi aundi": "insomnia",
    "haddiyan dard": "bone_pain",
    "jodaan dard": "joint_pain",
    "sir dard": "headache",
    "vaal jhadna": "hair_loss",
    "vaal girna": "hair_loss",
    "nakhun toot jaande": "brittle_nails",
    "bhukh nahi lagdi": "loss_of_appetite",
    "chakkar aande": "dizziness",
    "saans aundi mushkil": "breathlessness",
    "rang safed": "pallor",
    "chakkar aana": "dizziness",
    "muh de chhaale": "mouth_ulcers",
    "daad": "skin_rashes",
    "khujli": "skin_rashes",
    "zakhm nahi bharda": "slow_wound_healing",
    "maanspeshiyan dard": "muscle_cramps",
    "pair sunn": "numbness_tingling",
    "hath sunn": "numbness_tingling",
    "jhanjhanahat": "numbness_tingling",
    "yaad nahi rehta": "memory_issues",
    "bhulna": "memory_issues",
    "udaasi": "depression",
    "raat nu nahi dikhda": "night_blindness",
    "akkhaan sukhiyan": "dry_eyes",
    "gala vich ganth": "goiter",
    "thand lagdi": "cold_intolerance",
    "khoon di kami": "iron_deficiency",
    "masde ton khoon": "bleeding_gums",
    "zabanah laal": "sore_tongue",
    "infection zyada": "frequent_infections",
}

ENGLISH_SYMPTOM_VARIATIONS = {
    "tired": "fatigue",
    "tiredness": "fatigue",
    "exhausted": "fatigue",
    "weakness": "fatigue",
    "weak": "fatigue",
    "always tired": "fatigue",
    "no energy": "fatigue",
    "hair falling": "hair_loss",
    "hair shedding": "hair_loss",
    "losing hair": "hair_loss",
    "nails breaking": "brittle_nails",
    "nails brittle": "brittle_nails",
    "cracked nails": "brittle_nails",
    "pale skin": "pallor",
    "white nails": "pallor",
    "feel cold": "cold_intolerance",
    "always cold": "cold_intolerance",
    "cold hands": "cold_hands_feet",
    "cold feet": "cold_hands_feet",
    "forget things": "memory_issues",
    "forgetful": "memory_issues",
    "cant concentrate": "memory_issues",
    "tingling": "numbness_tingling",
    "pins and needles": "numbness_tingling",
    "numb": "numbness_tingling",
    "sad": "depression",
    "low mood": "depression",
    "joint pain": "joint_pain",
    "bone pain": "bone_pain",
    "muscle cramps": "muscle_cramps",
    "leg cramps": "muscle_cramps",
    "night cramps": "muscle_cramps",
    "night blindness": "night_blindness",
    "cant see at night": "night_blindness",
    "dry eyes": "dry_eyes",
    "itchy eyes": "dry_eyes",
    "bleeding gums": "bleeding_gums",
    "gums bleed": "bleeding_gums",
    "mouth sores": "mouth_ulcers",
    "canker sores": "mouth_ulcers",
    "swollen tongue": "sore_tongue",
    "sore tongue": "sore_tongue",
    "skin dry": "dry_skin",
    "rash": "skin_rashes",
    "wounds wont heal": "slow_wound_healing",
    "cuts dont heal": "slow_wound_healing",
    "frequent illness": "frequent_infections",
    "always sick": "frequent_infections",
    "get sick often": "frequent_infections",
    "neck swelling": "goiter",
    "throat lump": "goiter",
    "white spots nails": "white_spots_nails",
    "palpitations": "irregular_heartbeat",
    "heart racing": "irregular_heartbeat",
    "constipation": "constipation",
    "stomach pain": "abdominal_pain",
    "headache": "headache",
    "dizziness": "dizziness",
    "breathless": "breathlessness",
    "short of breath": "breathlessness",
    "insomnia": "insomnia",
    "cant sleep": "insomnia",
    "anxiety": "anxiety",
    "worried": "anxiety",
    "weight gain": "weight_gain",
}

ALL_SYMPTOM_MAPS = {}
ALL_SYMPTOM_MAPS.update(HINDI_SYMPTOM_MAP)
ALL_SYMPTOM_MAPS.update(PUNJABI_SYMPTOM_MAP)
ALL_SYMPTOM_MAPS.update(ENGLISH_SYMPTOM_VARIATIONS)

DIET_QUESTIONS_HINDI = [
    ("is_vegetarian", ["kya aap shakahari hain", "kya aap veg khate hain", "meat nahi khate"]),
    ("is_vegan", ["kya aap vegan hain", "dairy nahi khate", "doodh nahi peete"]),
    ("eats_fish", ["kya aap machli khate hain", "fish khate ho", "seafood khate"]),
    ("eats_dairy", ["kya aap doodh peete hain", "dahi khate hain", "dairy products"]),
    ("eats_eggs", ["kya aap ande khate hain", "eggs khate ho"]),
    ("eats_leafy_greens_daily", ["kya aap palak khate hain", "saag roz khate", "hari sabziyan"]),
    ("outdoor_sun_exposure_hrs", ["kitni der dhoop mein rehte hain", "sun exposure", "bahar rehte ho"]),
    ("uses_iodized_salt", ["kya iodized namak use karte hain", "aayodine wala namak"]),
]
